### PR TITLE
Preserves existing Markdown styles

### PR DESCRIPTION
**Pull request by nrichards**
Addresses #4 

* Change styling technique to one which introduces explicit SPAN elements. This avoids prior collisions with styling existing Markdown styles such as bold.
* Change extension for file storing CSS to match its contents for maintainability's sake
* Update example folder with new test

New example:

image

### CODE REVIEW

**Comment by nrichards** [comment]
Bugs in this PR: 
* Style for removed needs strikethrough. 
* Style for added needs bold.

**Comment by nrichards** [comment]
Fixed! I hope you like @jduckles

**Comment by jduckles** [comment]
Oooh very nice catch, thanks for taking the time to contribute a fix!

**Comment by nrichards** [comment]
FYI I used this change for https://github.com/raspy135/Qun-mk2/pull/17 to help describe changes I made to a Markdown for this synthesizer

**Comment by jduckles** [comment]
Very nice @nrichards! I created it when I was working on membership contracts for The Carpentries which I managed in markdown and needed to send red-line edit versions of what changed as part of the membership contract negotiations. You can also get a similar effect by using Word or LibreOffice and merging a changed version of the document with "track changes" turned on. I like this approach in text land a lot more though. Happy to see it being useful.

**Pull request merged**
